### ISSUE TITLE
aggiungere autore del post quando presente

### ISSUE THREAD

**Issue by larsen** [Haskell-ITA/www_haskell-ita_it_website#11]

**Comment by massimo-zaniboni** [comment]
Fatto. In realta`lo aggiungo sempre ma per le pagine generiche usa "community". Faccio cosi` perche` non ho voglia di "litigare" con Hakyll per inserire del codice che francamente in PHP con tutti i suoi demeriti era probabilmente immediato fare. Odio Hakyll.
