### ISSUE TITLE
Ridurre dimensioni foto meetup di Firenze

### ISSUE THREAD

**Issue by massimo-zaniboni** [Haskell-ITA/www_haskell-ita_it_website#24]
La foto del meetup di Firenze puo` essere scalata.

**Comment by fgaz** [comment]
La cosa migliore sarebbe metterla scalata con un link a quella a risoluzione piena, che forse si può anche fare in automatico

**Comment by fgaz** [comment]
fatto: 3f34297
ora il caricamento è decisamente più veloce
