### ISSUE TITLE
L'icona BUILD-STATUS in home-page del repo ha poco senso

### ISSUE THREAD

**Issue by massimo-zaniboni** [Haskell-ITA/www_haskell-ita_it_website#25]
Su https://github.com/Haskell-ITA/www_haskell-ita_it_website c'e` una icona di build-statu, ma punta a gitlab.com e github "si offende" e non la fa vedere. 

Io sarei per toglierla.

**Comment by massimo-zaniboni** [comment]
Ah no in notevole ritardo ma poi la fa vedere. Boh decidete voi se tenerla o meno.

**Comment by fgaz** [comment]
Secondo me è carina, fa vedere a colpo docchio se è successo qualche casino nella compilazione
